version: '3.8'

services:
    api:
        build: ./api
        restart: always
        expose:
            - '3000'
        environment:
            PORT: 3000
            DATABASE_URL: postgresql://postgres:postgres_dev@postgres:5432/reiz
            SECRET: ${API_SECRET}
            SALT: ${API_SALT}
            TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}
            TELEGRAM_CHAT_ID: ${TELEGRAM_CHAT_ID}
            CORS_ORIGINS: https://reiz.com.ua
            SERVICE_SECRET: ${SERVICE_SECRET}
        volumes:
            - ./api/uploads:/usr/src/app/uploads
        depends_on:
            postgres:
                condition: service_healthy
        networks:
            - reiz

    web:
        build:
            context: ./front
            dockerfile: Dockerfile
            args:
                NEXT_PUBLIC_TURNSTILE_SITE_KEY: ${NEXT_PUBLIC_TURNSTILE_SITE_KEY}
        image: my-next-app:latest
        environment:
            NODE_ENV: production
            HOSTNAME: 0.0.0.0
            PORT: 8080
            DATABASE_URL: postgresql://postgres:postgres_dev@postgres:5432/reiz
            AUTH_SECRET: ${AUTH_SECRET}
            AUTH_TRUST_HOST: "true"
            AUTH_URL: https://reiz.com.ua
            GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
            GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
            SERVICE_SECRET: ${SERVICE_SECRET}
            API_URL_INTERNAL: http://api:3000/api
            NEXT_PUBLIC_BASE_URL: https://reiz.com.ua/
            NEXT_PUBLIC_TURNSTILE_SITE_KEY: ${NEXT_PUBLIC_TURNSTILE_SITE_KEY}
            TURNSTILE_SECRET_KEY: ${TURNSTILE_SECRET_KEY}
        expose:
            - "8080"
        restart: always
        volumes:
            - next_cache:/app/.next/cache
        networks:
            - reiz

    postgres:
        image: postgres:16
        restart: always
        expose:
            - '5432'
        volumes:
            - pgdata:/var/lib/postgresql/data
        environment:
            POSTGRES_DB: reiz
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres_dev
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U postgres -d reiz"]
            interval: 5s
            timeout: 5s
            retries: 10
        networks:
            - reiz
    
    caddy:
        image: caddy:2.7
        restart: always
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./Caddyfile:/etc/caddy/Caddyfile
            - caddy_data:/data
            - caddy_config:/config
        networks:
            - reiz

volumes:
    pgdata:
    caddy_data:
    caddy_config:
    next_cache:

networks:
    reiz:
