-- AlterTable
ALTER TABLE "Car" ALTER COLUMN "brand" DROP NOT NULL,
ALTER COLUMN "model" DROP NOT NULL,
ALTER COLUMN "plate_number" DROP NOT NULL,
ALTER COLUMN "VIN" DROP NOT NULL,
ALTER COLUMN "year_of_manufacture" DROP NOT NULL,
ALTER COLUMN "segment_id" DROP NOT NULL;
